/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Wishwa
 */
public class ViewGuarantorWindow extends javax.swing.JFrame {

    /**
     * Creates new form ViewGuarantorWindow
     */
    public ViewGuarantorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtSearchGuarantor = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblSearchUser = new javax.swing.JLabel();
        lblSearchFrom = new javax.swing.JLabel();
        checkGuarantorId = new javax.swing.JCheckBox();
        checkGuarantorName = new javax.swing.JCheckBox();
        btnSearchGuarantor = new javax.swing.JButton();
        btnDeleteGuarantor = new javax.swing.JButton();
        btnUpdateGuarantor = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtSearchGuarantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 311, -1));

        lblWelcome.setText("Welcome: User name");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 112, -1, -1));

        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 144, 90, 20));

        lblTime.setText("Time:");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 175, 90, 20));

        lblSearchUser.setBackground(new java.awt.Color(102, 102, 102));
        lblSearchUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchUser.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchUser.setText("View Guarantor");
        getContentPane().add(lblSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 28));

        lblSearchFrom.setText("Search By");
        getContentPane().add(lblSearchFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 60, 30));

        buttonGroup1.add(checkGuarantorId);
        checkGuarantorId.setSelected(true);
        checkGuarantorId.setText("Guarantor Id");
        checkGuarantorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGuarantorIdselectionChanged(evt);
            }
        });
        getContentPane().add(checkGuarantorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 70, 100, -1));

        buttonGroup1.add(checkGuarantorName);
        checkGuarantorName.setText("Name");
        checkGuarantorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGuarantorNameActionPerformed(evt);
            }
        });
        getContentPane().add(checkGuarantorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 77, -1));

        btnSearchGuarantor.setText("Search");
        btnSearchGuarantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGuarantorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchGuarantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 102, 106, -1));

        btnDeleteGuarantor.setText("Delete");
        btnDeleteGuarantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGuarantorActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteGuarantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 329, 210, 30));

        btnUpdateGuarantor.setText("Update");
        btnUpdateGuarantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGuarantorActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateGuarantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 329, 209, 30));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 71, 132, -1));

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User Id", "Name", "Contact No", "Address", "Member Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 440, 180));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkGuarantorIdselectionChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGuarantorIdselectionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGuarantorIdselectionChanged

    private void btnSearchGuarantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGuarantorActionPerformed

        //Query is created in Data Access
        //Logic is in Controller
    }//GEN-LAST:event_btnSearchGuarantorActionPerformed

    private void btnDeleteGuarantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGuarantorActionPerformed

    }//GEN-LAST:event_btnDeleteGuarantorActionPerformed

    private void btnUpdateGuarantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGuarantorActionPerformed

    }//GEN-LAST:event_btnUpdateGuarantorActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

    }//GEN-LAST:event_btnHomeActionPerformed

    private void checkGuarantorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGuarantorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGuarantorNameActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteGuarantor;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearchGuarantor;
    private javax.swing.JButton btnUpdateGuarantor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkGuarantorId;
    private javax.swing.JCheckBox checkGuarantorName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSearchFrom;
    private javax.swing.JLabel lblSearchUser;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtSearchGuarantor;
    // End of variables declaration//GEN-END:variables

  
    /**
     * @return the btnHome
     */
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }

    /**
     * @return the lblDate
     */
    public javax.swing.JLabel getLblDate() {
        return lblDate;
    }

    /**
     * @return the lblTime
     */
    public javax.swing.JLabel getLblTime() {
        return lblTime;
    }

    /**
     * @return the lblWelcome
     */
    public javax.swing.JLabel getLblWelcome() {
        return lblWelcome;
    }

    /**
     * @return the tblSearch
     */
    public javax.swing.JTable getTblSearch() {
        return tblSearch;
    }

    /**
     * @return the txtSearchUser
     */
    public javax.swing.JTextField getTxtSearchUser() {
        return getTxtSearchGuarantor();
    }

    /**
     * @return the btnDeleteGuarantor
     */
    public javax.swing.JButton getBtnDeleteGuarantor() {
        return btnDeleteGuarantor;
    }

    /**
     * @return the btnSearchGuarantor
     */
    public javax.swing.JButton getBtnSearchGuarantor() {
        return btnSearchGuarantor;
    }

    /**
     * @return the btnUpdateGuarantor
     */
    public javax.swing.JButton getBtnUpdateGuarantor() {
        return btnUpdateGuarantor;
    }

    /**
     * @return the checkGuarantorId
     */
    public javax.swing.JCheckBox getCheckGuarantorId() {
        return checkGuarantorId;
    }

    /**
     * @return the checkGuarantorName
     */
    public javax.swing.JCheckBox getCheckGuarantorName() {
        return checkGuarantorName;
    }

    /**
     * @return the txtSearchGuarantor
     */
    public javax.swing.JTextField getTxtSearchGuarantor() {
        return txtSearchGuarantor;
    }
}
