/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author wijerath_ps13257
 */
public class ViewBookCopyWindow extends javax.swing.JFrame {

    /**
     * Creates new form ViewBookCopyWindow
     */
    public ViewBookCopyWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        btnDeleteBookCopy = new javax.swing.JButton();
        btnUpdateBookCopy = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearchBookCopy = new javax.swing.JTextField();
        checkBookCopyName = new javax.swing.JCheckBox();
        checkBookCopyId = new javax.swing.JCheckBox();
        lblSearchFrom = new javax.swing.JLabel();
        lblSearchUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Copy Id", "Book Copy Name", "Book Id", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 440, 140));

        btnDeleteBookCopy.setText("Delete");
        btnDeleteBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookCopyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBookCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 30));

        btnUpdateBookCopy.setText("Update");
        btnUpdateBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookCopyActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateBookCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 209, 30));

        lblTime.setText("Time:");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 175, 90, 20));

        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 144, 90, 20));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 71, 132, -1));

        lblWelcome.setText("Welcome: User name");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 112, -1, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 102, 106, -1));
        getContentPane().add(txtSearchBookCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 311, -1));

        buttonGroup1.add(checkBookCopyName);
        checkBookCopyName.setText("Book Copy Name");
        checkBookCopyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBookCopyNameActionPerformed(evt);
            }
        });
        getContentPane().add(checkBookCopyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 140, -1));

        buttonGroup1.add(checkBookCopyId);
        checkBookCopyId.setSelected(true);
        checkBookCopyId.setText("Book Copy Id");
        checkBookCopyId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBookCopyIdselectionChanged(evt);
            }
        });
        getContentPane().add(checkBookCopyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 70, 100, -1));

        lblSearchFrom.setText("Search By");
        getContentPane().add(lblSearchFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 60, 30));

        lblSearchUser.setBackground(new java.awt.Color(102, 102, 102));
        lblSearchUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchUser.setForeground(new java.awt.Color(102, 102, 102));
        lblSearchUser.setText("View Book Copy");
        getContentPane().add(lblSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookCopyActionPerformed

    }//GEN-LAST:event_btnDeleteBookCopyActionPerformed

    private void btnUpdateBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookCopyActionPerformed

    }//GEN-LAST:event_btnUpdateBookCopyActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        //Query is created in Data Access
        //Logic is in Controller
    }//GEN-LAST:event_btnSearchActionPerformed

    private void checkBookCopyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBookCopyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBookCopyNameActionPerformed

    private void checkBookCopyIdselectionChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBookCopyIdselectionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBookCopyIdselectionChanged

    public JButton getBtnDeleteBookCopy() {
        return btnDeleteBookCopy;
    }

    public JButton getBtnHome() {
        return btnHome;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public JButton getBtnUpdateBookCopy() {
        return btnUpdateBookCopy;
    }

    public JCheckBox getCheckBookCopyId() {
        return checkBookCopyId;
    }

    public JCheckBox getCheckBookCopyName() {
        return checkBookCopyName;
    }

    public JLabel getLblDate() {
        return lblDate;
    }

    public JLabel getLblTime() {
        return lblTime;
    }

    public JLabel getLblWelcome() {
        return lblWelcome;
    }

    public JTable getTblSearch() {
        return tblSearch;
    }

    public JTextField getTxtSearchBookCopy() {
        return txtSearchBookCopy;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteBookCopy;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateBookCopy;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBookCopyId;
    private javax.swing.JCheckBox checkBookCopyName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSearchFrom;
    private javax.swing.JLabel lblSearchUser;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtSearchBookCopy;
    // End of variables declaration//GEN-END:variables
}
