
package View;

/**
 *
 * @author Wishwa
 */
public class ViewMemberWindow extends javax.swing.JFrame {

    /**
     * Creates new form ViewMemberWindow
     */
    public ViewMemberWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lblWelcome = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblSearchFrom = new javax.swing.JLabel();
        lblSearchUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        checkMemberId = new javax.swing.JCheckBox();
        checkMemberName = new javax.swing.JCheckBox();
        txtSearchMember = new javax.swing.JTextField();
        btnSearchMember = new javax.swing.JButton();
        btnViewGuarantor = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        btnUpdateMember = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setText("Welcome: User name");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 112, -1, -1));

        lblTime.setText("Time:");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 175, 90, 20));

        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 144, 90, 20));

        lblSearchFrom.setText("Search By");
        getContentPane().add(lblSearchFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 60, 30));

        lblSearchUser.setBackground(new java.awt.Color(102, 102, 102));
        lblSearchUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchUser.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchUser.setText("View Member");
        getContentPane().add(lblSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 28));

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User Id", "Name", "Contact No", "Address", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 427, 180));

        buttonGroup.add(checkMemberId);
        checkMemberId.setSelected(true);
        checkMemberId.setText("Member Id");
        checkMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMemberIdselectionChanged(evt);
            }
        });
        getContentPane().add(checkMemberId, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 70, 77, -1));

        buttonGroup.add(checkMemberName);
        checkMemberName.setText("Name");
        getContentPane().add(checkMemberName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 77, -1));
        getContentPane().add(txtSearchMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 311, -1));

        btnSearchMember.setText("Search");
        btnSearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 102, 106, -1));

        btnViewGuarantor.setText("View Guarantor");
        getContentPane().add(btnViewGuarantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 120, -1));

        btnDeleteMember.setText("Delete");
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 329, 210, 30));

        btnUpdateMember.setText("Update");
        btnUpdateMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMemberActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 329, 209, 30));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 71, 132, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed

    }//GEN-LAST:event_btnDeleteMemberActionPerformed

    private void btnSearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberActionPerformed

        //Query is created in Data Access
        //Logic is in Controller
    }//GEN-LAST:event_btnSearchMemberActionPerformed

    private void btnUpdateMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMemberActionPerformed

    }//GEN-LAST:event_btnUpdateMemberActionPerformed

    private void checkMemberIdselectionChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMemberIdselectionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMemberIdselectionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearchMember;
    private javax.swing.JButton btnUpdateMember;
    private javax.swing.JButton btnViewGuarantor;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox checkMemberId;
    private javax.swing.JCheckBox checkMemberName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSearchFrom;
    private javax.swing.JLabel lblSearchUser;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtSearchMember;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnDeleteUser
     */
    public javax.swing.JButton getBtnDeleteUser() {
        return btnDeleteMember;
    }

    /**
     * @return the btnHome
     */
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }

    /**
     * @return the btnSearchUser
     */
    public javax.swing.JButton getBtnSearchUser() {
        return btnSearchMember;
    }

    /**
     * @return the btnUpdateUser
     */
    public javax.swing.JButton getBtnUpdateUser() {
        return btnUpdateMember;
    }

    /**
     * @return the buttonGroup
     */
    public javax.swing.ButtonGroup getButtonGroup() {
        return buttonGroup;
    }

    /**
     * @return the checkName
     */
    public javax.swing.JCheckBox getCheckName() {
        return getCheckMemberName();
    }

    /**
     * @return the checkUserId
     */
    public javax.swing.JCheckBox getCheckUserId() {
        return getCheckMemberId();
    }

    /**
     * @return the lblDate
     */
    public javax.swing.JLabel getLblDate() {
        return lblDate;
    }

    /**
     * @return the lblTime
     */
    public javax.swing.JLabel getLblTime() {
        return lblTime;
    }

    /**
     * @return the lblWelcome
     */
    public javax.swing.JLabel getLblWelcome() {
        return lblWelcome;
    }

    /**
     * @return the tblSearch
     */
    public javax.swing.JTable getTblSearch() {
        return tblSearch;
    }

    /**
     * @return the txtSearchUser
     */
    public javax.swing.JTextField getTxtSearchUser() {
        return txtSearchMember;
    }

    /**
     * @return the checkMemberId
     */
    public javax.swing.JCheckBox getCheckMemberId() {
        return checkMemberId;
    }

    /**
     * @return the checkMemberName
     */
    public javax.swing.JCheckBox getCheckMemberName() {
        return checkMemberName;
    }

    /**
     * @return the btnViewGuarantor
     */
    public javax.swing.JButton getBtnViewGuarantor() {
        return btnViewGuarantor;
    }
}
